export enum TableStatus {
  FREE = 'FREE',
  OCCUPIED = 'OCCUPIED',
  WAITING_ORDER = 'WAITING_ORDER',
  IN_PREPARATION = 'IN_PREPARATION',
  WAITING_PAYMENT = 'WAITING_PAYMENT',
  CLOSED = 'CLOSED',
}
